name: delus_messenger
description: Delus Messenger! Written by Flutter & Dart!
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Navigation
  auto_route: ^7.8.4
  
  # Network & HTTP
  http: ^1.2.1
  dio: ^5.4.3+1
  
  # Storage & Preferences
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Media & Files
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  photo_view: ^0.15.0
  flutter_image_gallery_saver: ^0.0.2
  path_provider: ^2.1.3
  
  # Audio & Voice
  record: ^6.1.1
  just_audio: ^0.9.36
  voice_message_package:
    git:
      url: https://github.com/sorydima/voice_message_package.git
      ref: 6a37ac9e332515c6dbd21d1dd60ec9e535adabac
  
  # Notifications
  onesignal_flutter: ^5.1.0
  
  # Utilities
  url_launcher: ^6.2.5
  crypto: ^3.0.3
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  uuid: ^4.3.3
  
  # Localization
  easy_localization: ^3.0.3
  timeago_flutter: ^3.5.0
  
  # UI Components
  flutter_slidable: ^4.0.1
  flutter_spinkit: ^5.2.0
  flutter_html: ^3.0.0-beta.2
  multi_select_flutter: ^4.1.3
  pinput: ^5.0.1
  qr_flutter: ^4.1.0
  syncfusion_flutter_sliders: ^25.1.41
  
  # Sharing & Social
  share_plus: ^11.1.0
  
  # Cache Management
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.10
  riverpod_generator: ^2.4.0
  
  # Linting & Analysis
  flutter_lints: ^6.0.0
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.8
  
  # Development Tools
  logger: ^2.0.2+1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/chat/
    - assets/images/icons/navbar/
    - assets/images/icons/settings/
    - assets/images/icons/social/
    - assets/images/snackbars/
    - assets/images/snackbars/types/
    - assets/translations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300

dependency_overrides:
  intl: 0.20.2
